config/routes.rb
Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'visitors#index-es'
  get 'en', to: 'visitors#index-en'
  #resources :users
  namespace :api do #namespace :api, path: "", constraints: {:subdomain => "api"} do
    namespace :v1 do
      get 'items', to: 'items#index'
      get 'items/:id', to: 'items#show'
      get 'items/search/:search_term', to: 'items#search'
      get 'companies', to: 'companies#index'
      get 'companies/:device_id', to: 'companies#index'
      get 'countries', to: 'locations#countries'
      get 'states', to: 'locations#states'
      get 'cities', to: 'locations#cities'
      post 'authenticate', to: 'authentication#authenticate'
    end
  end


end

app/models/item.rb
class Item < ApplicationRecord
  #scope :recently_updated, -> { where('updated_at >= ?', Date.today - 2.hours) }
  #has_paper_trail
  belongs_to :company
  has_and_belongs_to_many :parents, inverse_of: :item,
                          join_table: 'item_relationships',
                          class_name: Item,
                          foreign_key: :item_id,
                          association_foreign_key: :parent_id,
                          uniq: true
  has_and_belongs_to_many :children, inverse_of: :item,
                          join_table: 'item_relationships',
                          class_name: Item,
                          foreign_key: :parent_id,
                          association_foreign_key: :item_id,
                          uniq: true

  #attr_accessor :attachments
  has_many :attachments
  accepts_nested_attributes_for :attachments, allow_destroy: true
  accepts_nested_attributes_for :parents, allow_destroy: true
  accepts_nested_attributes_for :children, allow_destroy: true

  has_many :item_categories, dependent: :destroy
  has_many :categories, through: :item_categories

  def my_categories
    self.categories.map(&:name)
  end

  def my_categories?(have_any_of_these)
    self if self.categories & have_any_of_these
  end

  # def extra_properties
  #   require 'json'
  #   JSON.parse(self.extra_properties)
  # end

end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < ApiController
  before_action :set_resource,  only: [:show]
  before_action :set_item_list, only: [:index, :search]

  def index
    box = /\(((?:-?\d*\.)?\d+),((?:-?\d*\.)?\d+)\),\(((?:-?\d*\.)?\d+),((?:-?\d*\.)?\d+)\)/.match(params[:box]) ? params[:box] : nil #if there's a bounding box, filter the items by that.
    point = /((?:-?\d*\.)?\d+),((?:-?\d*\.)?\d+)/.match(params[:point]) ? params[:point] : nil
    country = params[:country]
    state = params[:state]
    city= params[:city]
    @item_list.where!(country: country) if country && state.nil? && city.nil?
    @item_list.where!(country: country, city: city) if country && state.nil? && city
    @item_list.where!(country: country, state: state) if country && state && city.nil?
    @item_list.where!(country: country, state: state, city: city) if country && state && city
    @item_list.where!([':box::box @> point(lat, lng)', {box: box}]) if box
    @item_list.where!(['(:point::point <-> point(lat, lng)) * 100000 < 100', {point: point}]) if point
    json_response @item_list, except: item_list_except_fields
  end

  def show
    json_response @resource, include: {
        attachments: {except: attachment_except_fields},
        company: {except: company_except_fields},
        #template: {except: template_except_fields},
        parents: {except: parents_except_fields},
        children: {except: parents_except_fields},
        categories: {except: categories_except_fields}
    }, except: item_except_fields
  end

  def search
    @item_list.where!('label ILIKE ?', "%#{params[:search_term]}%")
    json_response @item_list, except: item_list_except_fields
  end

  private

  def template_except_fields
    (generic_except_fields << %w(label description color_reference lat lng enabled is_template is_root company_id item_id)).flatten
  end

  def parents_except_fields
    (generic_except_fields << %w(is_template is_root company_id item_id country state city extra_properties)).flatten
  end

  def categories_except_fields
    (template_except_fields << %w(extra_properties)).flatten
  end

  def attachment_except_fields
    (generic_except_fields << %w(id)).flatten
  end

  def company_except_fields
    (generic_except_fields << %w(enabled)).flatten
  end

  def generic_except_fields
    %w(qrcode company_id item_id created_at updated_at)
  end

  def item_except_fields
    %w(qrcode company_id item_id country state city)
  end

  def item_list_except_fields
    (item_except_fields << generic_except_fields << %w(enabled is_template is_root extra_properties)).flatten
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_resource
    if @current_user.admin?
      @resource = Item.includes(:item_categories).where(id: params[:id], enabled: true)
    else
      @resource = Item.includes(:item_categories)
                      .where(id: params[:id], enabled: true,
                             item_categories: {category_id: current_user.categories.map(&:id)}) #has my current categories
    end
  end

  def set_item_list
    if @current_user.admin?
      @item_list = Item.includes(:item_categories)
    else
      @item_list= Item.includes(:item_categories)
                 .where(enabled: true,
                        item_categories: {category_id: current_user.categories.map(&:id)}) #has my current categories
    end
  end
end

app/views/items/_form.html.erb
<%= simple_form_for @item , html: {multipart: true}  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :id %>
    <%= f.input :label %>
    <%= f.input :qrcode %>
    <%#= f.input :properties, as: :text %>
    <%= f.input :enabled %>
    <%= f.input :is_root %>
    <%= f.input :is_template %>
    <%= f.input :company_id %>

        <p>
          <label>Documents</label>
        </p>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Label</th>
      <th>Qrcode</th>
      <th>Properties</th>
      <th>Enabled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.label %></td>
        <td><%= item.extra_properties %></td>
        <td><%= item.enabled %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Id:</strong>
  <%= @item.id %>
</p>

<p>
  <strong>Label:</strong>
  <%= @item.label %>
</p>

<p>
  <strong>Qrcode:</strong>
  <%= @qr = RQRCode::QRCode.new( item.id, :size => 4, :level => :h ) %>
</p>

<p>
  <strong>Properties:</strong>
  <br/>
  <% @item.extra_properties.keys.each do |p|%>
      <%= p %> : <%= @item.extra_properties[p] %>
  <% end %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @item.enabled %>
</p>

<label>Documents</label>
<table>
  <% @item.attachments.each do |doc| %>
  <tr>
    <td>
      <%= doc.document.file.filename %>
    </td>
    <td>
      <%= image_tag(doc.document.url) %>
    </td>
  </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>