config/routes.rb
Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'visitors#index-es'
  get 'en', to: 'visitors#index-en'
  #resources :users
  namespace :api do #namespace :api, path: "", constraints: {:subdomain => "api"} do
    namespace :v1 do
      get 'items', to: 'items#index'
      get 'items/:id', to: 'items#show'
      get 'items/search/:search_term', to: 'items#search'
      get 'companies', to: 'companies#index'
      get 'companies/:device_id', to: 'companies#index'
      get 'countries', to: 'locations#countries'
      get 'states', to: 'locations#states'
      get 'cities', to: 'locations#cities'
      post 'authenticate', to: 'authentication#authenticate'
    end
  end


end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <!--<li><#%= link_to t('edit_account'), edit_user_registration_path %></li>-->
  <!--<li><#%= link_to t('sign_out'), destroy_user_session_path, :method=>'delete' %></li>-->
<% else %>
  <!--<li><#%= link_to t('sign_in'), new_user_session_path %></li>-->
  <!--<li><#%= link_to t('sign_up'),  new_user_registration_path %></li>-->
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <!--<li><#%= link_to 'Users', users_path %></li>-->
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('Home'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to t('about'), page_path('about') %></li>
<% if current_user %>
<li><%= link_to t('log_out'), destroy_user_session_path  %></li>
<% end %>

app/views/layouts/_version.html.erb
<% if !@versions.empty? %>
    <h3>Current Version: <%= @versions.length %></h3>

    <b>Created At:</b>
    <%= @versions.last.created_at%>
    <br>
    <b>Admin</b>: <%= User.find(@versions.last.whodunnit).email %>
    <br>
    <% if @versions.length.to_i > 1 %>
        <% if params[:version].to_i > 1 || !params[:version] %>
            <%= link_to "Previous version", {:version => (params[:version] || @versions.length).to_i - 1}%>
            <br>
        <% end %>
        <% if params[:version] %>
            <h3>This is <%= "#{params[:version]}"%> version</h3>

            <b>Modify at:</b>
            <%= @versions[(params[:version].to_i - 1)].created_at %>
            <br>
            <b>Admin</b>:
            <%= User.find(@versions[(params[:version].to_i - 1)].whodunnit).email %>
            <br>

            <%= link_to "Go to current version"%>
        <% end %>
    <% end %>
<% else %>
    <p>This item does not have any registered version.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ScanApp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : Rails.application.class.parent %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= render 'peek/bar' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/old.application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "MyScanApp" %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : Rails.application.class.parent %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Js -->
  <script>window.jQuery || document.write('<script src="jquery-1.10.2.min.js"><\/script>')</script>
  <script>
      new WOW(
      ).init();
  </script>
</head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%#= render 'peek/bar' %>
      <%= yield %>
    </main>
  </body>
</html>